baseURL = "http://hugo-market-digitalgarage-template-test.apps.thedigitalgarage.io"
languageCode = "en-us"
title = "My Product Marketplace"
theme = "market"
SectionPagesMenu = "main"
disableKinds=["RSS"]

[params]
  description = "a site for displaying product info, built with Docker containers and other app builders in mind"
  welcome = "Welcome to Our Marketplace"
  title = "Our Business Name"
